"""add user_name to appointmens table

Revision ID: 0f6e42c58b72
Revises: 292becb0ea0e
Create Date: 2024-02-14 17:45:40.988550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f6e42c58b72'
down_revision: Union[str, None] = '292becb0ea0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('user_name', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'user_name')
    # ### end Alembic commands ###
