"""init tables

Revision ID: 292becb0ea0e
Revises: 
Create Date: 2023-11-30 13:41:08.345154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '292becb0ea0e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('master_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('package_type', sa.Enum('UNDEFINED', 'FIRST', 'SECOND', 'THIRD', 'EXTRA', name='package'), nullable=True),
    sa.Column('procedure_time', sa.DateTime(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('is_provided', sa.Boolean(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
    sa.Column('elapsed_time', sa.DateTime(), nullable=True),
    sa.Column('final_cost', sa.DECIMAL(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('master_id', sa.BigInteger(), nullable=True),
    sa.Column('external_master_id', sa.Integer(), nullable=True),
    sa.Column('date_time_slot', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'MASTER', 'ADMINISTRATOR', name='role'), nullable=True),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('whatsApp', sa.String(length=50), nullable=True),
    sa.Column('telegram', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('loyal_level', sa.Enum('NONE', 'ONE', 'TWO', 'THREE', 'FOUR', 'FIVE', name='loyalty'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_users_chat_id'), 'users', ['chat_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_chat_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('slots')
    op.drop_table('appointments')
    # ### end Alembic commands ###
